In [2]:
import osmnx as ox
import geopandas as gpd

In [4]:
df = gpd.read_file("../../data/partOfKarlsruhe.geojson")
df

                   name                                           geometry
0  Karlsruher Zoogarten  POLYGON ((8.39751 49.00125, 8.39751 48.99546, ...
1    Karlsruher Schloss  POLYGON ((8.40366 49.01429, 8.40366 49.01293, ...

In [7]:
# downlaod the data
karl = ox.geometries_from_polygon(df["geometry"][0], tags={"building": True})
karl

                                                                  geometry  \
element_type osmid
node         4728572193                           POINT (8.39939 48.99869)
way          15526552    POLYGON ((8.40249 49.00122, 8.40249 49.00121, ...
             15526579    POLYGON ((8.40237 49.00085, 8.40237 49.00086, ...
             43539595    POLYGON ((8.40148 48.99863, 8.40151 48.99855, ...
             43539597    POLYGON ((8.40313 48.99741, 8.40314 48.99739, ...
...                                                                    ...
             1095324741  POLYGON ((8.40220 48.99618, 8.40219 48.99619, ...
             1095324742  POLYGON ((8.40220 48.99618, 8.40224 48.99616, ...
relation     4854902     POLYGON ((8.40220 49.00168, 8.40221 49.00172, ...
             8184250     POLYGON ((8.39856 48.99901, 8.39873 48.99834, ...
             8184251     POLYGON ((8.39801 48.99828, 8.39798 48.99859, ...

                        access wheelchair wheelchair:description description  \
element_type osmid
node         4728572193    NaN        yes                    NaN         NaN
way          15526552      NaN        NaN                    NaN         NaN
             15526579      NaN        yes                    NaN         NaN
             43539595      NaN        NaN                    NaN         NaN
             43539597      NaN        NaN                    NaN         NaN
...                        ...        ...                    ...         ...
             1095324741    NaN        NaN                    NaN         NaN
             1095324742    NaN        NaN                    NaN         NaN
relation     4854902       NaN        NaN                    NaN         NaN
             8184250       NaN        NaN                    NaN         NaN
             8184251       NaN        NaN                    NaN         NaN

                                   name tourism           amenity  \
element_type osmid
node         4728572193  Shintō-Schrein     NaN  place_of_worship
way          15526552       Gartenhalle     NaN   exhibition_hall
             15526579               NaN     NaN               NaN
             43539595    Dickhäuterhaus     NaN               NaN
             43539597      Giraffenhaus     NaN               NaN
...                                 ...     ...               ...
             1095324741             NaN     NaN               NaN
             1095324742             NaN     NaN               NaN
relation     4854902                NaN     NaN               NaN
             8184250                NaN     NaN               NaN
             8184251                NaN     NaN               NaN

                                building religion  ... building:architecture  \
element_type osmid                                 ...
node         4728572193           shrine   shinto  ...                   NaN
way          15526552    exhibition_hall      NaN  ...                   NaN
             15526579              civic      NaN  ...                   NaN
             43539595                zoo      NaN  ...                   NaN
             43539597                zoo      NaN  ...                   NaN
...                                  ...      ...  ...                   ...
             1095324741           aviary      NaN  ...                   NaN
             1095324742           aviary      NaN  ...                   NaN
relation     4854902               civic      NaN  ...       neo-renaissance
             8184250                roof      NaN  ...                   NaN
             8184251                roof      NaN  ...                   NaN

                        teahouse min_height alt_name note material     zoo  \
element_type osmid
node         4728572193      NaN        NaN      NaN  NaN      NaN     NaN
way          15526552        NaN        NaN      NaN  NaN      NaN     NaN
             15526579        NaN        NaN      NaN  NaN      NaN     NaN
             43539595        NaN        NaN      NaN  NaN      NaN     NaN
             43539597        NaN        NaN      NaN  NaN      NaN     NaN
...                          ...        ...      ...  ...      ...     ...
             1095324741      NaN        NaN      NaN  NaN      NaN  aviary
             1095324742      NaN        NaN      NaN  NaN      NaN  aviary
relation     4854902         NaN        NaN      NaN  NaN      NaN     NaN
             8184250         NaN        NaN      NaN  NaN      NaN     NaN
             8184251         NaN        NaN      NaN  NaN      NaN     NaN

                                           ways  \
element_type osmid
node         4728572193                     NaN
way          15526552                       NaN
             15526579                       NaN
             43539595                       NaN
             43539597                       NaN
...                                         ...
             1095324741                     NaN
             1095324742                     NaN
relation     4854902      [15526564, 342153240]
             8184250     [539726002, 539726018]
             8184251     [539726005, 539726006]

                                           heritage:description          type
element_type osmid
node         4728572193                                     NaN           NaN
way          15526552                                       NaN           NaN
             15526579                                       NaN           NaN
             43539595                                       NaN           NaN
             43539597                                       NaN           NaN
...                                                         ...           ...
             1095324741                                     NaN           NaN
             1095324742                                     NaN           NaN
relation     4854902     Kulturdenkmal von besonderer Bedeutung  multipolygon
             8184250                                        NaN  multipolygon
             8184251                                        NaN  multipolygon

[268 rows x 84 columns]